### ISSUE TITLE
[ BUG ] Wrong filename in Github Action (the trailing ".md" should be removed)

### ISSUE THREAD

**Issue by etienne-sf** [ekalinin/github-markdown-toc#113]
To start with: thank you for this __great__ Markdown enhancement!

**Describe the bug**
I added a github action in the [graphql-maven-plugin-project'wiki](https://github.com/graphql-java-generator/graphql-maven-plugin-project/).
The issue is that the URL in the generated TOC doesn't work.

You can check on [this file](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server)

https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server.md#graphql-maven-plugin-server-mode-usage

**Expected behavior**

The generated link is:
```
https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server.md#graphql-maven-plugin-server-mode-usage
```

But it should be:
```
https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server#graphql-maven-plugin-server-mode-usage
```

The difference is the `server` and not `server.md` as the file name, at the end of the path.

Perhaps there is a parameter to manage that, but I did not find it.

**Environment (please complete the following information):**
I'm execution the github action with this action file:
```
# This is a basic workflow to help you get started with Actions

name: Wiki TOC

# Controls when the action will run. 
on:
  # Triggers the workflow on any change on the wiki (on the master branch)
  #gollum:    # This is triggered each time a file is changed on the wiki, including when the this script automatically run!
  
  # Below: push on the wiki, for the master branch 
  #push:
  #  paths:
  #    - 'wiki/**'
  #  branches:
  #    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "toc"
  toc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
      - run: |
          ls
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup *.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update markdown TOC
```
