### ISSUE TITLE
[ BUG ] github action not work (code in README.md)

### ISSUE THREAD

**Issue by Onyx-Nostalgia** [ekalinin/github-markdown-toc#156]
github action not work (code in README.md)

```yml
on:
  push:
    branches: [main]
    paths: ['foo.md']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.8.0/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup --hide-footer foo.md
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update markdown TOC
```

Output: table content is empty 
![image](https://github.com/user-attachments/assets/15bf04ea-52d4-4b90-ba05-7e56802213f3)

Because: curl install  version `0.8.0`
```
curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.8.0/gh-md-toc -o gh-md-toc
```

Sol: Update your README.md

change `0.8.0` -> `master`
```
curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.8.0/gh-md-toc -o gh-md-toc
```
